#!/bin/bash

echo "package main" > pkgs.go 

echo "" >> pkgs.go
echo "// THIS FILE WAS AUTOMATICALLY GENERATED BY genpkgs.sh" >> pkgs.go
echo "" >> pkgs.go

echo "var stdPkgs = map[string]struct{}{" >> pkgs.go

# list all standard packages using the `go list` tool
go list -f '{{ if ne .Name "main"}}"{{ .ImportPath }}":struct{}{},{{ end }}' std >> pkgs.go

# the magic "C" import is not listed in standard packages
echo '"C":struct{}{},' >> pkgs.go

echo "}" >> pkgs.go

gofmt -w pkgs.go
